# Generated by Django 6.0.6 on 2026-07-04 10:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Admin',
            fields=[
                ('adminid', models.IntegerField(primary_key=True, serialize=False)),
                ('adminname', models.CharField(blank=True, db_column='adminName', max_length=255, null=True)),
                ('adminnumber', models.IntegerField(blank=True, db_column='adminNumber', null=True)),
                ('adminemail', models.CharField(blank=True, db_column='adminEmail', max_length=255, null=True)),
                ('adminpwd', models.CharField(db_column='adminPwd', max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'admin',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Categories',
            fields=[
                ('catergoryid', models.IntegerField(db_column='catergoryId', primary_key=True, serialize=False)),
                ('catergorytype', models.CharField(blank=True, db_column='Catergorytype', max_length=255, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'categories',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('customername', models.CharField(blank=True, db_column='CustomerName', max_length=255, null=True)),
                ('customerid', models.IntegerField(db_column='customerId', primary_key=True, serialize=False)),
                ('email', models.CharField(blank=True, max_length=255, null=True)),
                ('phonenumber', models.CharField(blank=True, db_column='phoneNumber', max_length=255, null=True)),
                ('address', models.CharField(blank=True, max_length=255, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'customer',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Orders',
            fields=[
                ('orderid', models.IntegerField(db_column='orderId', primary_key=True, serialize=False)),
                ('catergoryid', models.IntegerField(blank=True, db_column='CatergoryId', null=True)),
                ('quantity', models.IntegerField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'orders',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Payments',
            fields=[
                ('paymentid', models.IntegerField(blank=True, db_column='paymentId', null=True, unique=True)),
                ('paymenttype', models.CharField(blank=True, db_column='PaymentType', max_length=255, null=True)),
                ('transactionid', models.IntegerField(db_column='TransactionId', primary_key=True, serialize=False)),
                ('orderid', models.IntegerField(blank=True, db_column='OrderId', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'payments',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Products',
            fields=[
                ('productid', models.IntegerField(primary_key=True, serialize=False)),
                ('productname', models.CharField(max_length=255)),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('photo_path', models.ImageField(upload_to='products/')),
                ('discounted_prices', models.DecimalField(decimal_places=2, max_digits=10)),
            ],
            options={
                'db_table': 'products',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Refund',
            fields=[
                ('refundid', models.IntegerField(primary_key=True, serialize=False)),
                ('amount', models.IntegerField()),
                ('refundtype', models.CharField(max_length=255)),
                ('refundreason', models.CharField(blank=True, db_column='refundReason', max_length=255, null=True)),
            ],
            options={
                'db_table': 'refund',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Reviews',
            fields=[
                ('reviewid', models.IntegerField(primary_key=True, serialize=False)),
                ('review', models.CharField(blank=True, db_column='Review', max_length=255, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('photo_path', models.CharField(blank=True, max_length=255, null=True)),
                ('uploaded_date', models.DateField()),
            ],
            options={
                'db_table': 'reviews',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Sale',
            fields=[
                ('saleid', models.IntegerField(primary_key=True, serialize=False)),
                ('salename', models.CharField(blank=True, db_column='saleName', max_length=255, null=True)),
                ('saleduration', models.IntegerField(blank=True, null=True)),
                ('salestart_date', models.DateTimeField(blank=True, null=True)),
                ('saleend_date', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'sale',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Seller',
            fields=[
                ('sellerid', models.IntegerField(primary_key=True, serialize=False)),
                ('sellername', models.CharField(blank=True, db_column='sellerName', max_length=255, null=True)),
                ('address', models.CharField(blank=True, max_length=255, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'seller',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Shipment',
            fields=[
                ('shipmentid', models.IntegerField(db_column='shipmentId', primary_key=True, serialize=False)),
                ('shipmentcompany', models.CharField(blank=True, db_column='shipmentCompany', max_length=255, null=True)),
                ('trackingid', models.CharField(blank=True, db_column='trackingId', max_length=255, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(blank=True, null=True)),
            ],
            options={
                'db_table': 'shipment',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Wishlist',
            fields=[
                ('wishlistid', models.IntegerField(db_column='wishlistId', primary_key=True, serialize=False)),
                ('wishlistitemquantity', models.IntegerField(blank=True, db_column='wishlistItemQuantity', null=True)),
                ('itemnames', models.CharField(blank=True, db_column='itemNames', max_length=255, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'wishlist',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='ProductVariant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('color', models.CharField(blank=True, max_length=100, null=True)),
                ('storage', models.CharField(blank=True, max_length=100, null=True)),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('discounted_price', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('stock', models.PositiveIntegerField(default=0)),
                ('photo', models.ImageField(blank=True, null=True, upload_to='variants/')),
                ('sku', models.CharField(blank=True, max_length=100, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('product', models.ForeignKey(db_column='product_id', on_delete=django.db.models.deletion.CASCADE, related_name='variants', to='store.products')),
            ],
            options={
                'db_table': 'product_variants',
                'unique_together': {('product', 'color', 'storage')},
            },
        ),
    ]
