# Generated by Django 6.0.6 on 2026-07-08 05:59
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0001_initial'),
    ]

    operations = [
        migrations.SeparateDatabaseAndState(
            state_operations=[
                migrations.AlterUniqueTogether(
                    name='productvariant',
                    unique_together={('product', 'color', 'storage', 'Size', 'Ram')},
                ),
            ],
            database_operations=[
                migrations.RunSQL(
                    sql="ALTER TABLE product_variants ADD CONSTRAINT product_variants_unique_variant UNIQUE (product_id, color, storage, `SIZE`, `RAM`);",
                    reverse_sql="ALTER TABLE product_variants DROP INDEX product_variants_unique_variant;",
                ),
            ],
        ),
        migrations.CreateModel(
            name='CartItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.PositiveIntegerField(default=1)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cart_items', to='store.customer')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='in_carts', to='store.products')),
                ('variant', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='in_carts', to='store.productvariant')),
            ],
            options={
                'db_table': 'cart_items',
                'unique_together': {('customer', 'product', 'variant')},
            },
        ),
    ]