# Generated by Django 6.0.6 on 2026-07-09 09:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0002_alter_productvariant_unique_together_and_more'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='productvariant',
            unique_together={('product', 'quantity', 'dosage_size')},
        ),
        migrations.AddField(
            model_name='productvariant',
            name='dosage_size',
            field=models.IntegerField(blank=True, db_column='Dosage_size', null=True),
        ),
        migrations.AddField(
            model_name='productvariant',
            name='quantity',
            field=models.IntegerField(blank=True, db_column='Quantity', null=True),
        ),
        migrations.RemoveField(
            model_name='productvariant',
            name='color',
        ),
        migrations.RemoveField(
            model_name='productvariant',
            name='sku',
        ),
        migrations.RemoveField(
            model_name='productvariant',
            name='storage',
        ),
    ]
